# Generated by Django 4.2.2 on 2023-06-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contents',
        ),
    ]
